<a href="https://colab.research.google.com/github/sankalprode104-stack/DEMOSYBAI-DS/blob/main/PracticalNo_3Sankalprode66.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name - Sankalp Vilas Rode

Class - Second year

Branch - AI&DS

Div - B

Roll No - 66

       PDS PRACTICAL NO.3

Aim : Data Wragling with pandas : Manipulate and transform data to suit the analysis needs

## 1. What is data wrangling, and why is it important before analysis?

Data wrangling, also known as data munging or data preprocessing, is the process of cleaning, transforming, and enriching raw data into a more suitable format for analysis. It involves steps like handling missing values, correcting inconsistencies, converting data types, and restructuring data. Data wrangling is crucial because real-world data is often messy, incomplete, and inconsistent. Without proper wrangling, analysis performed on such data can lead to inaccurate insights, misleading conclusions, and unreliable models. It ensures the data quality, accuracy, and usability, which are foundational for effective data analysis and decision-making.

## 2. You receive messy data with missing values, duplicates, and wrong types. What steps will you follow to clean it?

When faced with messy data, I would follow these steps to clean it:

1.  **Understand the Data:** Start by performing initial exploratory data analysis (EDA) to get a general overview of the dataset. Check dimensions, column names, and a few rows to understand its structure.
2.  **Handle Missing Values:** Identify missing values using methods like `df.isnull().sum()`. Decide on an imputation strategy based on the nature of the data and the extent of missingness. Options include dropping rows/columns, imputing with mean, median, mode, or using more advanced techniques like K-Nearest Neighbors (KNN) imputation.
3.  **Address Duplicates:** Detect and remove duplicate rows using `df.duplicated().sum()` and `df.drop_duplicates()`. For specific columns, identify and handle duplicates if they are not expected.
4.  **Correct Data Types:** Inspect data types using `df.info()`. Convert columns to appropriate types (e.g., objects to datetime, numbers stored as strings to numeric types) using `pd.to_datetime()`, `pd.to_numeric()`, or `df.astype()`. Incorrect data types can hinder calculations and lead to errors.
5.  **Standardize Text Data:** For categorical or text columns, clean inconsistencies such as varying cases ('USA', 'usa'), leading/trailing spaces (`.str.strip()`), or typos. Consider mapping similar values to a consistent representation.
6.  **Handle Outliers:** Identify outliers using statistical methods (e.g., Z-score, IQR) or visualization techniques (e.g., box plots). Decide whether to remove, transform, or cap outliers based on domain knowledge and their impact on analysis.
7.  **Data Validation:** Verify that the data adheres to expected rules and constraints (e.g., age cannot be negative, percentages should be between 0 and 100).
8.  **Rename Columns:** Ensure column names are clear, consistent, and easy to work with (e.g., lowercase, no spaces or special characters).

These steps ensure the data is clean, consistent, and ready for further analysis.

## 3. How can you check column names, data types, and summary statistics? What does "info()" show that "describe()" does not?

To check column names, data types, and summary statistics in pandas:

*   **Column Names:** Use `df.columns` to get a list of all column names.
*   **Data Types:** Use `df.dtypes` to view the data type of each column, or `df.info()` for a more comprehensive summary including non-null counts.
*   **Summary Statistics:** Use `df.describe()` to generate descriptive statistics (count, mean, std, min, 25%, 50%, 75%, max) for numerical columns.

### `info()` vs. `describe()`:

*   **`df.info()`** provides a concise summary of a DataFrame, including:
    *   The total number of entries.
    *   The number of columns.
    *   Each column's name, its non-null count, and its data type (Dtype).
    *   Memory usage of the DataFrame.
    *   It's particularly useful for quickly identifying missing values (by looking at non-null counts) and confirming data types.

*   **`df.describe()`** generates descriptive statistics of the DataFrame's numerical columns (by default) or all columns (if `include='all'` is specified). It shows:
    *   **Count:** Number of non-null observations.
    *   **Mean:** Average value.
    *   **Std:** Standard deviation.
    *   **Min/Max:** Minimum and maximum values.
    *   **25%, 50% (Median), 75%:** Percentiles (quartiles).
    *   For object (string) or categorical columns (with `include='all'`), it provides `count`, `unique`, `top`, and `freq`.

**What `info()` shows that `describe()` does not:**

`info()` primarily focuses on the **structure and completeness** of the data. It explicitly shows the **non-null counts** for each column, making it easy to spot columns with missing values without needing to perform a separate sum. It also displays the **memory usage** of the DataFrame. `describe()`, on the other hand, focuses on the **statistical distribution and central tendencies** of the data.

In essence, `info()` is for understanding the *metadata* and *quality* of the data, while `describe()` is for understanding the *statistical properties* and *distribution* of the values within the data.

## 4. How do you identify missing values and outliers in a dataset?

### Identifying Missing Values:

Missing values are common in real-world datasets and can be identified using several methods in pandas:

1.  **`df.isnull()` or `df.isna()`:** These methods return a boolean DataFrame of the same shape as `df`, indicating `True` for missing values (NaN, None, NaT) and `False` otherwise.
2.  **`df.isnull().sum()`:** This is a very common and efficient way to get a count of missing values for each column. It sums the `True` values from the boolean DataFrame generated by `isnull()`.
3.  **`df.isnull().sum().sum()`:** This gives the total number of missing values across the entire DataFrame.
4.  **`df.isnull().mean()`:** This calculates the percentage of missing values for each column, which can be useful for deciding whether to drop or impute a column.
5.  **Visualizations:** Heatmaps (`seaborn.heatmap(df.isnull())`) can visually represent the distribution of missing values, making patterns more apparent.

### Identifying Outliers:

Outliers are data points that significantly differ from other observations and can be identified through statistical methods and visualizations:

1.  **Statistical Methods:**
    *   **Z-score:** For normally distributed data, a Z-score measures how many standard deviations away a data point is from the mean. Values with an absolute Z-score greater than a certain threshold (e.g., 2 or 3) are often considered outliers.
    *   **Interquartile Range (IQR):** For non-normally distributed data, the IQR method is robust. Outliers are typically defined as values that fall below `Q1 - 1.5 * IQR` or above `Q3 + 1.5 * IQR`, where Q1 is the first quartile, Q3 is the third quartile, and IQR = Q3 - Q1.

2.  **Visualizations:**
    *   **Box Plots:** These are excellent for visualizing the distribution of numerical data and clearly show potential outliers as individual points beyond the 'whiskers' (which typically represent the IQR bounds).
    *   **Histograms/Density Plots:** These can show the overall distribution and help identify data points that are far removed from the main bulk of the data.
    *   **Scatter Plots:** For two variables, scatter plots can reveal bivariate outliers or clusters that deviate from the general trend. For high-dimensional data, techniques like PCA can reduce dimensionality for visualization.

## 5. How do you reduce memory usage in pandas DataFrames?

Reducing memory usage in pandas DataFrames is crucial, especially when working with large datasets, to improve performance and avoid memory errors. Here are several effective strategies:

1.  **Downcasting Numerical Types:** By default, pandas often uses `int64` and `float64` for numerical columns, which consume more memory than necessary if the actual range of values is smaller. You can downcast these to smaller types like `int8`, `int16`, `int32`, `float16`, or `float32`.
    *   Use `df.info(memory_usage='deep')` to see current memory usage.
    *   Iterate through numerical columns and use `df[col] = pd.to_numeric(df[col], downcast='integer')` or `df[col] = pd.to_numeric(df[col], downcast='float')`.

2.  **Convert `object` (string) columns to `category` type:** String columns often consume a significant amount of memory because each string is stored individually. If a string column has a limited number of unique values (low cardinality), converting it to the `category` data type can drastically reduce memory usage. Pandas stores categorical data more efficiently using integer codes.
    *   Use `df[col] = df[col].astype('category')` for appropriate columns.

3.  **Select Specific Columns:** If you don't need all columns from a large dataset, only load or keep the necessary ones. This directly reduces the amount of data in memory.

4.  **Use Efficient Data Structures (if applicable):** While not directly a DataFrame optimization, consider if a pandas Series or NumPy array is sufficient for a task instead of a full DataFrame if only one column is needed.

5.  **Remove Unnecessary Objects:** After processing, if intermediate DataFrames or large variables are no longer needed, explicitly delete them using `del variable_name` to free up memory. You can also trigger garbage collection with `import gc; gc.collect()`.

6.  **Chunking Data for Loading:** When reading very large files, instead of loading the entire file into memory at once, read it in chunks. This can be done using the `chunksize` parameter in `pd.read_csv()` or similar functions. Process each chunk and then combine the results, or only keep necessary aggregations in memory.

By systematically applying these techniques, you can significantly optimize memory usage in pandas, allowing for more efficient processing of larger datasets.

## Data Wrangling with Pandas Tasks

### Setting up Sample DataFrames

In [ ]:
import pandas as pd
import numpy as np

# Sample DataFrame for most operations (df)
data = {
    'Student_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Age': [20, 22, 21, 20, 23, 21, 22, 20, 23, 21],
    'Course': ['Math', 'Physics', 'Chem', 'Math', 'Physics', 'Chem', 'Math', 'Physics', 'Chem', 'Math'],
    'Score': [85, 92, 78, 88, 95, 80, 89, 91, 75, 84],
    'Attendance': [0.9, 0.95, 0.88, 0.92, 0.96, 0.85, 0.93, 0.90, 0.87, 0.94],
    'Enrollment_Date': pd.to_datetime(['2023-09-01', '2023-09-05', '2023-09-10', '2023-09-01', '2023-09-05',
                                         '2023-09-10', '2023-09-01', '2023-09-05', '2023-09-10', '2023-09-01'])
}
df = pd.DataFrame(data)
df.loc[2, 'Score'] = np.nan # Introduce a missing value
df.loc[4, 'Name'] = 'eve' # Introduce inconsistency

# Sample DataFrame for merging (df_grades)
grades_data = {
    'Student_ID': [1, 2, 3, 4, 5, 11],
    'Grade': ['A', 'A+', 'B', 'A', 'A+', 'C']
}
df_grades = pd.DataFrame(grades_data)

# Sample DataFrame for pivot/melt (df_sales)
sales_data = {
    'Region': ['East', 'West', 'East', 'West'],
    'Product_A': [100, 150, 110, 160],
    'Product_B': [200, 180, 210, 190],
    'Product_C': [50, 60, 55, 65]
}
df_sales = pd.DataFrame(sales_data)

print("Original DataFrame (df):")
display(df)
print("Grades DataFrame (df_grades):")
display(df_grades)
print("Sales DataFrame (df_sales):")
display(df_sales)

Original DataFrame (df):

   Student_ID     Name  Age   Course  Score  Attendance Enrollment_Date
0           1    Alice   20     Math   85.0        0.90      2023-09-01
1           2      Bob   22  Physics   92.0        0.95      2023-09-05
2           3  Charlie   21     Chem    NaN        0.88      2023-09-10
3           4    David   20     Math   88.0        0.92      2023-09-01
4           5      eve   23  Physics   95.0        0.96      2023-09-05
5           6    Frank   21     Chem   80.0        0.85      2023-09-10
6           7    Grace   22     Math   89.0        0.93      2023-09-01
7           8    Heidi   20  Physics   91.0        0.90      2023-09-05
8           9     Ivan   23     Chem   75.0        0.87      2023-09-10
9          10     Judy   21     Math   84.0        0.94      2023-09-01

Grades DataFrame (df_grades):

   Student_ID Grade
0           1     A
1           2    A+
2           3     B
3           4     A
4           5    A+
5          11     C

Sales DataFrame (df_sales):

  Region  Product_A  Product_B  Product_C
0   East        100        200         50
1   West        150        180         60
2   East        110        210         55
3   West        160        190         65

### Weak Students (Basic)

In [ ]:
# 1. Select a single column from a DataFrame.
print("1. Select 'Name' column:")
display(df['Name'].head())

# 2. Add a new column with constant values.
df['Status'] = 'Active'
print("\n2. DataFrame with new 'Status' column:")
display(df.head())

# 3. Sort a DataFrame by one column.
print("\n3. DataFrame sorted by 'Score' (ascending):")
display(df.sort_values(by='Score').head())

# 4. Rename DataFrame columns.
df_renamed = df.rename(columns={'Student_ID': 'ID', 'Score': 'Final_Score'})
print("\n4. DataFrame with renamed columns:")
display(df_renamed.head())

# 5. Display summary statistics using describe().
print("\n5. Summary statistics of the DataFrame:")
display(df.describe())

1. Select 'Name' column:

0      Alice
1        Bob
2    Charlie
3      David
4        eve
Name: Name, dtype: object

2. DataFrame with new 'Status' column:

,Student_ID,Name,Age,Course,Score,Attendance,Enrollment_Date,Status
0,1,Alice,20,Math,85.0,0.90,2023-09-01,Active
1,2,Bob,22,Physics,92.0,0.95,2023-09-05,Active
2,3,Charlie,21,Chem,NaN,0.88,2023-09-10,Active
3,4,David,20,Math,88.0,0.92,2023-09-01,Active
4,5,eve,23,Physics,95.0,0.96,2023-09-05,Active

3. DataFrame sorted by 'Score' (ascending):

   Student_ID   Name  Age Course  Score  Attendance Enrollment_Date  Status
8           9   Ivan   23   Chem   75.0        0.87      2023-09-10  Active
5           6  Frank   21   Chem   80.0        0.85      2023-09-10  Active
9          10   Judy   21   Math   84.0        0.94      2023-09-01  Active
0           1  Alice   20   Math   85.0        0.90      2023-09-01  Active
3           4  David   20   Math   88.0        0.92      2023-09-01  Active

4. DataFrame with renamed columns:

   ID     Name  Age   Course  Final_Score  Attendance Enrollment_Date  Status
0   1    Alice   20     Math         85.0        0.90      2023-09-01  Active
1   2      Bob   22  Physics         92.0        0.95      2023-09-05  Active
2   3  Charlie   21     Chem          NaN        0.88      2023-09-10  Active
3   4    David   20     Math         88.0        0.92      2023-09-01  Active
4   5      eve   23  Physics         95.0        0.96      2023-09-05  Active

5. Summary statistics of the DataFrame:

       Student_ID        Age      Score  Attendance      Enrollment_Date
count    10.00000  10.000000   9.000000   10.000000                   10
mean      5.50000  21.300000  86.555556    0.910000  2023-09-04 21:36:00
min       1.00000  20.000000  75.000000    0.850000  2023-09-01 00:00:00
25%       3.25000  20.250000  84.000000    0.885000  2023-09-01 00:00:00
50%       5.50000  21.000000  88.000000    0.910000  2023-09-05 00:00:00
75%       7.75000  22.000000  91.000000    0.937500  2023-09-08 18:00:00
max      10.00000  23.000000  95.000000    0.960000  2023-09-10 00:00:00
std       3.02765   1.159502   6.267199    0.036209                  NaN

### Normal Students (Moderate)

In [ ]:
# 6. Filter rows using multiple conditions.
# Students older than 20 AND in 'Math' or 'Physics' course
filtered_df = df[(df['Age'] > 20) & ((df['Course'] == 'Math') | (df['Course'] == 'Physics'))]
print("6. Filtered DataFrame (Age > 20 AND Course is Math or Physics):")
display(filtered_df)

# 7. Group data by a categorical column and calculate mean.
# Mean score per course
mean_score_by_course = df.groupby('Course')['Score'].mean().reset_index()
print("\n7. Mean score by Course:")
display(mean_score_by_course)

# 8. Merge two DataFrames on a common column.
merged_df = pd.merge(df, df_grades, on='Student_ID', how='left')
print("\n8. Merged DataFrame (df with df_grades):")
display(merged_df)

# 9. Drop rows and columns using pandas functions.
# Drop a column
df_dropped_col = df.drop(columns=['Attendance'])
print("\n9. DataFrame after dropping 'Attendance' column:")
display(df_dropped_col.head())

# Drop rows with NaN values (e.g., missing Score)
df_dropped_row = df.dropna(subset=['Score'])
print("\n   DataFrame after dropping rows with missing 'Score':")
display(df_dropped_row)

# 10. Apply a simple function to a column.
# Convert scores to a pass/fail status (assuming pass >= 80)
df['Pass_Fail'] = df['Score'].apply(lambda x: 'Pass' if x >= 80 else ('Fail' if pd.notna(x) else 'N/A'))
print("\n10. DataFrame with 'Pass_Fail' column:")
display(df)

6. Filtered DataFrame (Age > 20 AND Course is Math or Physics):

   Student_ID   Name  Age   Course  Score  Attendance Enrollment_Date  Status
1           2    Bob   22  Physics   92.0        0.95      2023-09-05  Active
4           5    eve   23  Physics   95.0        0.96      2023-09-05  Active
6           7  Grace   22     Math   89.0        0.93      2023-09-01  Active
9          10   Judy   21     Math   84.0        0.94      2023-09-01  Active

7. Mean score by Course:

    Course      Score
0     Chem  77.500000
1     Math  86.500000
2  Physics  92.666667

8. Merged DataFrame (df with df_grades):

,Student_ID,Name,Age,Course,Score,Attendance,Enrollment_Date,Status,Grade
0,1,Alice,20,Math,85.0,0.90,2023-09-01,Active,A
1,2,Bob,22,Physics,92.0,0.95,2023-09-05,Active,A+
2,3,Charlie,21,Chem,NaN,0.88,2023-09-10,Active,B
3,4,David,20,Math,88.0,0.92,2023-09-01,Active,A
4,5,eve,23,Physics,95.0,0.96,2023-09-05,Active,A+
5,6,Frank,21,Chem,80.0,0.85,2023-09-10,Active,NaN
6,7,Grace,22,Math,89.0,0.93,2023-09-01,Active,NaN
7,8,Heidi,20,Physics,91.0,0.90,2023-09-05,Active,NaN
8,9,Ivan,23,Chem,75.0,0.87,2023-09-10,Active,NaN
9,10,Judy,21,Math,84.0,0.94,2023-09-01,Active,NaN

9. DataFrame after dropping 'Attendance' column:

   Student_ID     Name  Age   Course  Score Enrollment_Date  Status
0           1    Alice   20     Math   85.0      2023-09-01  Active
1           2      Bob   22  Physics   92.0      2023-09-05  Active
2           3  Charlie   21     Chem    NaN      2023-09-10  Active
3           4    David   20     Math   88.0      2023-09-01  Active
4           5      eve   23  Physics   95.0      2023-09-05  Active

   DataFrame after dropping rows with missing 'Score':

   Student_ID   Name  Age   Course  Score  Attendance Enrollment_Date  Status
0           1  Alice   20     Math   85.0        0.90      2023-09-01  Active
1           2    Bob   22  Physics   92.0        0.95      2023-09-05  Active
3           4  David   20     Math   88.0        0.92      2023-09-01  Active
4           5    eve   23  Physics   95.0        0.96      2023-09-05  Active
5           6  Frank   21     Chem   80.0        0.85      2023-09-10  Active
6           7  Grace   22     Math   89.0        0.93      2023-09-01  Active
7           8  Heidi   20  Physics   91.0        0.90      2023-09-05  Active
8           9   Ivan   23     Chem   75.0        0.87      2023-09-10  Active
9          10   Judy   21     Math   84.0        0.94      2023-09-01  Active

10. DataFrame with 'Pass_Fail' column:

,Student_ID,Name,Age,Course,Score,Attendance,Enrollment_Date,Status,Pass_Fail
0,1,Alice,20,Math,85.0,0.90,2023-09-01,Active,Pass
1,2,Bob,22,Physics,92.0,0.95,2023-09-05,Active,Pass
2,3,Charlie,21,Chem,NaN,0.88,2023-09-10,Active,N/A
3,4,David,20,Math,88.0,0.92,2023-09-01,Active,Pass
4,5,eve,23,Physics,95.0,0.96,2023-09-05,Active,Pass
5,6,Frank,21,Chem,80.0,0.85,2023-09-10,Active,Pass
6,7,Grace,22,Math,89.0,0.93,2023-09-01,Active,Pass
7,8,Heidi,20,Physics,91.0,0.90,2023-09-05,Active,Pass
8,9,Ivan,23,Chem,75.0,0.87,2023-09-10,Active,Fail
9,10,Judy,21,Math,84.0,0.94,2023-09-01,Active,Pass

### Bright Students (Advanced)

In [ ]:
# 11. Perform pivot and melt operations on a dataset.

# Pivot: Transform df_sales from wide to long format for analysis by Product
pivoted_sales = df_sales.pivot_table(index='Region', values=['Product_A', 'Product_B', 'Product_C'], aggfunc='sum')
print("11. Pivoted Sales Data (sum of products by Region):")
display(pivoted_sales)

# Melt: Transform df_sales from wide to long format (e.g., for plotting)
melted_sales = df_sales.melt(id_vars=['Region'], var_name='Product', value_name='Sales_Value')
print("\n    Melted Sales Data (long format):")
display(melted_sales)

# 12. Implement multilevel indexing.
# Group by Course and then by Age
multi_indexed_df = df.set_index(['Course', 'Age']).sort_index()
print("\n12. DataFrame with MultiIndex (Course, Age):")
display(multi_indexed_df)

# Accessing data with multilevel index
print("\n    Data for 'Math' course (using MultiIndex):")
display(multi_indexed_df.loc['Math'])

# 13. Compare merge v/s join operations.
print("\n13. Merge vs Join Operations:")
print("   - **Merge (pd.merge()):** A function in pandas that combines two DataFrames or named Series objects based on common columns or indices. It's highly flexible, allowing various join types (inner, left, right, outer) and specifying join keys.")
print("   - **Join (df.join()):** A DataFrame method that combines two DataFrames on their indexes. It's a convenient method for performing a left join (by default) when one DataFrame's index aligns with the column or index of another. Less flexible than `merge` for arbitrary column-based joins.")
print("\n   *Example of `join` (joining df_grades onto df using index after setting 'Student_ID' as index in df):*")
df_indexed = df.set_index('Student_ID')
df_grades_indexed = df_grades.set_index('Student_ID')
joined_df = df_indexed.join(df_grades_indexed, how='left')
print("   Joined DataFrame (using .join()):")
display(joined_df)

# 14. Create custom aggregation functions.
# Custom aggregation: Calculate the range (max - min) of scores for each course
def score_range(series):
    return series.max() - series.min()

custom_agg_df = df.groupby('Course')['Score'].agg(['mean', score_range]).reset_index()
print("\n14. Custom aggregation (Mean and Range of Scores by Course):")
display(custom_agg_df)

# 15. Perform time series based data wrangling.
# First, ensure 'Enrollment_Date' is datetime type (already done in setup)
df['Enrollment_Date'] = pd.to_datetime(df['Enrollment_Date'])

# Extract year, month, day of week
df['Enrollment_Year'] = df['Enrollment_Date'].dt.year
df['Enrollment_Month'] = df['Enrollment_Date'].dt.month
df['Enrollment_DayOfWeek'] = df['Enrollment_Date'].dt.day_name()
print("\n15. DataFrame with Time Series Features (Year, Month, Day of Week):")
display(df.head())

# Group by month and count enrollments
monthly_enrollments = df.groupby('Enrollment_Month')['Student_ID'].count().reset_index()
print("\n    Monthly Enrollments:")
display(monthly_enrollments)

11. Pivoted Sales Data (sum of products by Region):

        Product_A  Product_B  Product_C
Region
East          210        410        105
West          310        370        125

    Melted Sales Data (long format):

   Region    Product  Sales_Value
0    East  Product_A          100
1    West  Product_A          150
2    East  Product_A          110
3    West  Product_A          160
4    East  Product_B          200
5    West  Product_B          180
6    East  Product_B          210
7    West  Product_B          190
8    East  Product_C           50
9    West  Product_C           60
10   East  Product_C           55
11   West  Product_C           65

12. DataFrame with MultiIndex (Course, Age):

             Student_ID     Name  Score  Attendance Enrollment_Date  Status  \
Course  Age
Chem    21            3  Charlie    NaN        0.88      2023-09-10  Active
        21            6    Frank   80.0        0.85      2023-09-10  Active
        23            9     Ivan   75.0        0.87      2023-09-10  Active
Math    20            1    Alice   85.0        0.90      2023-09-01  Active
        20            4    David   88.0        0.92      2023-09-01  Active
        21           10     Judy   84.0        0.94      2023-09-01  Active
        22            7    Grace   89.0        0.93      2023-09-01  Active
Physics 20            8    Heidi   91.0        0.90      2023-09-05  Active
        22            2      Bob   92.0        0.95      2023-09-05  Active
        23            5      eve   95.0        0.96      2023-09-05  Active

            Pass_Fail
Course  Age
Chem    21        N/A
        21       Pass
        23       Fail
Math    20       Pass
        20       Pass
        21       Pass
        22       Pass
Physics 20       Pass
        22       Pass
        23       Pass

    Data for 'Math' course (using MultiIndex):

     Student_ID   Name  Score  Attendance Enrollment_Date  Status Pass_Fail
Age
20            1  Alice   85.0        0.90      2023-09-01  Active      Pass
20            4  David   88.0        0.92      2023-09-01  Active      Pass
21           10   Judy   84.0        0.94      2023-09-01  Active      Pass
22            7  Grace   89.0        0.93      2023-09-01  Active      Pass

13. Merge vs Join Operations:
   - **Merge (pd.merge()):** A function in pandas that combines two DataFrames or named Series objects based on common columns or indices. It's highly flexible, allowing various join types (inner, left, right, outer) and specifying join keys.
   - **Join (df.join()):** A DataFrame method that combines two DataFrames on their indexes. It's a convenient method for performing a left join (by default) when one DataFrame's index aligns with the column or index of another. Less flexible than `merge` for arbitrary column-based joins.

   *Example of `join` (joining df_grades onto df using index after setting 'Student_ID' as index in df):*
   Joined DataFrame (using .join()):

,Name,Age,Course,Score,Attendance,Enrollment_Date,Status,Pass_Fail,Grade
Student_ID,,,,,,,,,
1,Alice,20,Math,85.0,0.90,2023-09-01,Active,Pass,A
2,Bob,22,Physics,92.0,0.95,2023-09-05,Active,Pass,A+
3,Charlie,21,Chem,NaN,0.88,2023-09-10,Active,N/A,B
4,David,20,Math,88.0,0.92,2023-09-01,Active,Pass,A
5,eve,23,Physics,95.0,0.96,2023-09-05,Active,Pass,A+
6,Frank,21,Chem,80.0,0.85,2023-09-10,Active,Pass,NaN
7,Grace,22,Math,89.0,0.93,2023-09-01,Active,Pass,NaN
8,Heidi,20,Physics,91.0,0.90,2023-09-05,Active,Pass,NaN
9,Ivan,23,Chem,75.0,0.87,2023-09-10,Active,Fail,NaN
10,Judy,21,Math,84.0,0.94,2023-09-01,Active,Pass,NaN

14. Custom aggregation (Mean and Range of Scores by Course):

    Course       mean  score_range
0     Chem  77.500000          5.0
1     Math  86.500000          5.0
2  Physics  92.666667          4.0

15. DataFrame with Time Series Features (Year, Month, Day of Week):

,Student_ID,Name,Age,Course,Score,Attendance,Enrollment_Date,Status,Pass_Fail,Enrollment_Year,Enrollment_Month,Enrollment_DayOfWeek
0,1,Alice,20,Math,85.0,0.90,2023-09-01,Active,Pass,2023,9,Friday
1,2,Bob,22,Physics,92.0,0.95,2023-09-05,Active,Pass,2023,9,Tuesday
2,3,Charlie,21,Chem,NaN,0.88,2023-09-10,Active,N/A,2023,9,Sunday
3,4,David,20,Math,88.0,0.92,2023-09-01,Active,Pass,2023,9,Friday
4,5,eve,23,Physics,95.0,0.96,2023-09-05,Active,Pass,2023,9,Tuesday

    Monthly Enrollments:

   Enrollment_Month  Student_ID
0                 9          10

## Conclusion

This notebook provided a comprehensive overview of various data wrangling techniques using the pandas library in Python. We explored basic operations such as selecting and adding columns, sorting, and renaming. Moving to moderate tasks, we demonstrated filtering with multiple conditions, grouping data for aggregation, merging DataFrames, and handling missing values and column drops.

For advanced users, we covered powerful transformations like pivot and melt operations, implemented multilevel indexing, compared `merge` and `join` functions, created custom aggregation functions, and performed time-series based data wrangling by extracting features from datetime columns. These examples illustrate the versatility of pandas in cleaning, transforming, and preparing data for effective analysis, irrespective of its initial state or complexity.